# Generated by Django 4.2.2 on 2023-07-21 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='number',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='User',
            new_name='user',
        ),
    ]
