# Generated by Django 4.2.2 on 2023-08-02 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='prduct',
            new_name='product',
        ),
    ]
