# Generated by Django 4.2.2 on 2023-09-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_customer_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='razorpay_order_id',
        ),
    ]
